In [1]:
import torch

In [5]:
tensor = torch.rand(1,2)
tensor
tensor = tensor.cuda()
tensor

tensor([[0.5129, 0.2725]])

tensor([[0.5129, 0.2725]], device='cuda:0')

In [7]:
device = torch.device('cuda:1')
tensor1 = tensor.to(device)
tensor1

tensor([[0.5129, 0.2725]], device='cuda:1')